version: 2

jobs:
  build:
    docker:
      - image: notnoopci/php:7.1.5-browsers
    working_directory: ~/whats-my-gate
    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit
      - run: bash <(curl -s https://codecov.io/bash) -t be997b73-a8cc-41c5-99ed-2030501a9619